server:
  port: 8888

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jeonwoojae/spring-cloud-config.git
#          if private
#          username:
#          password:
#          uri: file:///Users/user/OneDrive - kumoh.ac.kr/study_msa/git-local-repo