server:
  port: 8888

spring:
  application:
    name: config-service
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: guest
    password: guest
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Jeonwoojae/spring-cloud-config.git
#          if private
#          username:
#          password:
#          uri: file:///Users/user/OneDrive - kumoh.ac.kr/study_msa/git-local-repo
management:
  endpoints:
    web:
      exposure:
        include: health, bus-refresh